name: usage_tracker
description: A Flutter plugin to track the total time an app is in the foreground over a specified date range, providing insights into app usage duration.
version: 0.0.1
homepage: https://github.com/Abdullahkhidr/usage_tracker_plugin

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: akm.usage_tracker.plugin
        pluginClass: UsageTrackerPlugin
