name: usage_tracker
description: "A Flutter plugin for tracking app usage data on Android, including time spent in foreground and other app usage metrics."
version: 0.0.1
homepage: https://github.com/yourusername/usage_tracker  # Replace with the actual GitHub or documentation link

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: akm.usage_tracker.plugin
        pluginClass: UsageTrackerPlugin

author:
  name: "Abdullah Khidr"
  email: "abdullahkhidr52@gmail.com"
